            - name: Close Stale Issues
  uses: actions/stale@v9.0.0
  with:
    # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
    stale-issue-message: Stale!
    # The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale.
    stale-pr-message: Stale!
    # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
    close-issue-message: Closing...
    # The message to post on the pull request when closing it. If none provided, will not comment when closing a pull requests.
    close-pr-message: Closing...
    # The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
    days-before-stale: 182.5
    # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues as stale automatically. Override "days-before-stale" option regarding only the issues.
    days-before-issue-stale: 182.5 
    # The number of days old a pull request can be before marking it stale. Set to -1 to never mark pull requests as stale automatically. Override "days-before-stale" option regarding only the pull requests.
    days-before-pr-stale: 182.5
    # The number of days to wait to close an issue or a pull request after it being marked stale. Set to -1 to never close stale issues or pull requests.
    days-before-close: 5
    # The number of days to wait to close an issue after it being marked stale. Set to -1 to never close stale issues. Override "days-before-close" option regarding only the issues.
    days-before-issue-close: 5
    # The number of days to wait to close a pull request after it being marked stale. Set to -1 to never close stale pull requests. Override "days-before-close" option regarding only the pull requests.
    days-before-pr-close: 5
    # The label to apply when an issue is stale.
    stale-issue-label: Stale
    # The label to apply when an issue is closed.
    close-issue-label: Closed
    # The labels that mean an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2").
    exempt-issue-labels: Cant-be-stale
    # The reason to use when closing an issue.
    close-issue-reason: # optional, default is not_planned
    # The label to apply when a pull request is stale.
    stale-pr-label: Stale
    # The label to apply when a pull request is closed.
    close-pr-label: Closed
    # The labels that mean a pull request is exempt from being marked as stale. Separate multiple labels with commas (eg. "label1,label2").
    exempt-pr-labels: Cant-be-stale
    # The maximum number of operations per run, used to control rate limiting (GitHub API CRUD related).
    operations-per-run: 50
    # The order to get issues or pull requests. Defaults to false, which is descending.
    ascending: true
    # Exempt draft pull requests from being marked as stale. Default to false.
    exempt-draft-pr: true
    # Display some statistics at the end regarding the stale workflow (only when the logs are enabled).
    enable-statistics: # optional, default is true
    # A comma delimited list of labels to add when an issue or pull request becomes unstale.
    labels-to-add-when-unstale: Unstale
    # A comma delimited list of labels to remove when an issue or pull request becomes stale.
    labels-to-remove-when-stale: Unstale
    # A comma delimited list of labels to remove when an issue or pull request becomes unstale.
    labels-to-remove-when-unstale: Stale
    # Any update (update/comment) can reset the stale idle time on the issues and pull requests.
    ignore-updates: true
          
